---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-react-app
  namespace: pokemon-react
  labels:
    app: pokemon-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-react-app
  template:
    metadata:
      labels:
        app: pokemon-react-app
    spec:
      containers:
        - name: pokemon-ui
          image: samwilk18/pokemon-react-ui:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 3
