---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-react-service
  namespace: pokemon-react
spec:
  selector:
    app: pokemon-react-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
