version: "3"

name: "pokemon-tracker-app"

services:
  pokemon-server:
    build:
      context: ./api
      dockerfile: Dev.Dockerfile
    env_file: ./api/.env.local
    ports:
      - "3000:3000"
    networks:
      - pokemon-network

  pokemon-ui:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - "88:80"
    networks:
      - pokemon-network

  pokemon-database:
    container_name: pokemon-database
    image: postgres:15-alpine
    restart: always
    ports:
      - "8080:5432"
    env_file: .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge

volumes:
  postgres_data:
