version: "3.9"

name: "pokemon-tracker-app"

services:
  pokemon-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  pokemon-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
