version: "3.9"

name: "pokemon-tracker-app"

services:
  pokemon-server:
    build:
      context: ./api
      dockerfile: Dev.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - pokemon-network

  pokemon-ui:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - "80:80"
    networks:
      - pokemon-network

  pokemon-database:
    container_name: pokemon-database
    image: postgres:15-alpine
    restart: always
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge

volumes:
  postgres_data:
