version: "3.9"

name: "pokemon-tracker-app"

services:
  pokemon-server:
    image: pokemon-react-server:latest
    ports:
      - "3000:3000"

  pokemon-ui:
    image: pokemon-react-ui:latest
    ports:
      - "4000:4000"

  nginx:
    image: test-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - pokemon-ui
      - pokemon-server
