name: Continuous Integration and Deployment

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  confirm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npm run build
  deploy:
    needs: confirm-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npm run build
      - run: git config --global user.email ${{ secrets.MY_EMAIL }}
      - run: git config --global user.name ${{ secrets.MY_USER_NAME }}
      - run: git init
      - run: git checkout -B main
      - run: git add dist -f
      - run: git commit -m "Adding dist to deploy"
      - run: git push -f https://github.com/SamWilk/pokemon-react.git main:gh-pages
