name: Continuous Integration

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
      - "development-branch"

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Creating .env file
        run: |
          echo "${{ secrets.PROD_ENV }}" > ./api/.env

  confirm-build:
    needs: create-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          npm ci
          npm run build

  build-docker-image:
    runs-on: ubuntu-latest
    needs: confirm-build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pokemon-react-ui:latest
