name: Continuous Integration and Deployment

on:
  push:
    branches:
      - "main"

permissions: write-all

jobs:
  # confirm-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #     - run: npm i
  #     - run: npm run build
  deploy:
    # needs: confirm-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - run: npm run build
      - run: git config --global user.email ${{ secrets.MY_EMAIL }}
      - run: git config --global user.name ${{ secrets.MY_USER_NAME }}
      - run: git remote set-url origin https://github.com/SamWilk/pokemon-react.git
      - run: npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
